# Generated by Django 3.2.8 on 2021-10-20 10:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20211020_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
